### ISSUE TITLE
Address open tasks for Part 2

### ISSUE THREAD

**Issue by j-i-l** [t4d-gmbh/git-and-its-remotes#9]
Part 2 along with Part 3 (probably) will be built in https://github.com/t4d-gmbh/git-and-its-remotes

The following tasks are needed for Part 2:

- [x] t4d-gmbh/git-and-its-remotes#1
- [ ] t4d-gmbh/git-and-its-remotes#4
- [ ] t4d-gmbh/git-and-its-remotes#3
- [ ] t4d-gmbh/git-and-its-remotes#5
- [ ] t4d-gmbh/git-and-its-remotes#6
- [ ] t4d-gmbh/git-and-its-remotes#7
- [ ] t4d-gmbh/git-and-its-remotes#8
